server:
  port: 80
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    #content - type: text/html
    mode: HTML5
  servlet:
    multipart:
      max-request-size: 100MB # \u4E0A\u4F20\u6587\u4EF6\u603B\u7684\u6700\u5927\u503C
      max-file-size: 100MB # \u5355\u4E2A\u6587\u4EF6\u7684\u6700\u5927\u503C
  devtools:
    restart:
      enabled: true
  #classpath\u76EE\u5F55\u4E0B\u7684WEB-INF\u6587\u4EF6\u5939\u5185\u5BB9\u4FEE\u6539\u4E0D\u91CD\u542F
  #spring.devtools.restart.exclude: WEB-INF/**
